apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-blue
  labels:
    app: flask-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      version: blue
  template:
    metadata:
      labels:
        app: flask-app
        version: blue
    spec:
      containers:
      - name: flask-app
        image: flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
