apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
    version: blue      # Start by routing to BLUE pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
