apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pp17704/self-hosted.git
    targetRevision: main
    path: gitops-apps/flask-app
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
